version: 2.1
orbs:
  docker: circleci/docker@1.0.0
workflows:
  deploy:
    jobs:
      - docker/publish:
         deploy: false
         image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
         tag: 'latest'
      - run:
          name: Push to heroku
          command: heroku container:login
